name: lint, test, build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  check-this-shit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production
        run: npm run build:prod
      - name: lint scss
        run: npm run lint:scss
      - name: lint ts
        run: npm run lint:ts
      - name: test unit
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: test ui
        run: npm run test:ui
